FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/cocodrilo-fitness/.next/static
COPY public ./apps/cocodrilo-fitness/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1
CMD ["node", "apps/cocodrilo-fitness/server.js"]
