FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/stroopwafel-huis/.next/static
COPY public ./apps/stroopwafel-huis/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/stroopwafel-huis/server.js"]
