services:
  web:
    image: tsuki-restaurante:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.tsuki-restaurante.entrypoints=websecure"
        - "traefik.http.routers.tsuki-restaurante.rule=Host(`tsuki-restaurante.paragu-ai.com`)"
        - "traefik.http.routers.tsuki-restaurante.tls=true"
        - "traefik.http.routers.tsuki-restaurante.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.tsuki-restaurante.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
