services:
  web:
    image: mantraspa:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.mantraspa.entrypoints=websecure"
        - "traefik.http.routers.mantraspa.rule=Host(`mantraspa.paragu-ai.com`)"
        - "traefik.http.routers.mantraspa.tls=true"
        - "traefik.http.routers.mantraspa.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mantraspa.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
