FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/fun4me/.next/static
COPY public ./apps/fun4me/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/fun4me/server.js"]
