services:
  web:
    image: fun4me:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.fun4me.entrypoints=websecure"
        - "traefik.http.routers.fun4me.rule=Host(`fun4me.paragu-ai.com`)"
        - "traefik.http.routers.fun4me.tls=true"
        - "traefik.http.routers.fun4me.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.fun4me.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
