FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/camilo-acosta/.next/static
COPY public ./apps/camilo-acosta/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/camilo-acosta/server.js"]
