FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000
COPY .next/standalone ./
COPY .next/static ./apps/la-serafina-site/.next/static
COPY public ./apps/la-serafina-site/public
EXPOSE 3000
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
USER nextjs
CMD ["node", "apps/la-serafina-site/server.js"]
