services:
  web:
    image: de-abasto-a-casa:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.de-abasto-a-casa.entrypoints=websecure"
        - "traefik.http.routers.de-abasto-a-casa.rule=Host(`de-abasto-a-casa.paragu-ai.com`)"
        - "traefik.http.routers.de-abasto-a-casa.tls=true"
        - "traefik.http.routers.de-abasto-a-casa.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.de-abasto-a-casa.middlewares=security-headers@file"
        - "traefik.http.services.de-abasto-a-casa.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
