FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --chown=nextjs:nodejs .next/standalone/ ./
COPY --chown=nextjs:nodejs .next/static ./apps/de-abasto-a-casa/.next/static
COPY --chown=nextjs:nodejs content apps/de-abasto-a-casa/content
COPY --chown=nextjs:nodejs public apps/de-abasto-a-casa/public
USER nextjs
EXPOSE 3000
WORKDIR /app/apps/de-abasto-a-casa
CMD ["node", "server.js"]
