services:
  web:
    image: dra-gabriela:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.dra-gabriela.entrypoints=websecure"
        - "traefik.http.routers.dra-gabriela.rule=Host(`dra-gabriela.com.py`) || Host(`www.dra-gabriela.com.py`) || Host(`dragabriela.paragu-ai.com`)"
        - "traefik.http.routers.dra-gabriela.tls=true"
        - "traefik.http.routers.dra-gabriela.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dra-gabriela.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
