/**
 * Static Site Configuration for Cloudflare Pages
 * This file is imported at build time to avoid Edge Runtime issues
 */

export const SITES = {
  'nexa-paraguay': {
    slug: 'nexa-paraguay',
    vertical: 'relocacion',
    country: 'Paraguay',
    domain: 'nexaparaguay.com',
    defaultLocale: 'nl',
    locales: ['nl', 'en', 'de', 'es'],
    pages: ['home', 'programas', 'por-que-paraguay', 'proceso', 'sobre', 'faq', 'blog', 'contacto', 'privacidad'],
  },
  'nexa-propiedades': {
    slug: 'nexa-propiedades',
    vertical: 'inmobiliaria',
    country: 'Paraguay',
    domain: 'nexapropiedades.com',
    defaultLocale: 'es',
    locales: ['es', 'en', 'pt'],
    pages: ['home', 'propiedades', 'servicios', 'equipo', 'testimonios', 'blog', 'contacto', 'privacidad'],
  },
  'fun4me': {
    slug: 'fun4me',
    vertical: 'retail-local',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'quienes-somos', 'suscripciones', 'bundles', 'placer-plus', 'gift-cards', 'loyalty', 'blog', 'legal', 'reserva-en-tienda', 'size-guide'],
  },
  'dayah-litworks': {
    slug: 'dayah-litworks',
    vertical: 'portfolio-professional',
    country: 'Paraguay',
    domain: 'dayah-litworks.com',
    defaultLocale: 'es',
    locales: ['es', 'en'],
    pages: ['home', 'servicios', 'catalogo', 'portafolio', 'faq', 'blog', 'contacto', 'sobre', 'terminos'],
  },
  'de-abasto-a-casa': {
    slug: 'de-abasto-a-casa',
    vertical: 'food-beverage',
    country: 'Paraguay',
    domain: 'deabastoacasa.com.py',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'menu', 'pedidos', 'zonas', 'galeria', 'blog', 'faq', 'contacto'],
  },
    vertical: 'agriculture-agribusiness',
    country: 'Paraguay',
    domain: 'granjacabral.com.py',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'blog', 'faq', 'contacto'],
  },
  'stoicfinch': {
    slug: 'stoicfinch',
    vertical: 'technology-digital',
    country: 'Canada',
    domain: 'stoicfinch.com',
    defaultLocale: 'en',
    locales: ['en'],
    pages: ['home', 'blog', 'pricing', 'faq', 'contacto'],
  },
  'nudo': {
    slug: 'nudo',
    vertical: 'arts-entertainment-venues',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'musica', 'videos', 'letras', 'shows', 'galeria', 'tienda', 'blog', 'contacto'],
  },
  'bufete-mendez': {
    slug: 'bufete-mendez',
    vertical: 'b2b-professional',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'servicios', 'equipo', 'casos', 'testimonios', 'faq', 'blog', 'contacto', 'privacidad', 'terminos'],
  },
  'demo-contador': {
    slug: 'demo-contador',
    vertical: 'b2b-professional',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'servicios', 'calculadoras', 'equipo', 'testimonios', 'faq', 'blog', 'contacto'],
  },
  'demo-estudio-contable': {
    slug: 'demo-estudio-contable',
    vertical: 'b2b-professional',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'servicios', 'calculadoras', 'equipo', 'faq', 'blog', 'contacto'],
  },
  'alejandro-villamayor': {
    slug: 'alejandro-villamayor',
    vertical: 'b2b-professional',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es', 'en'],
    pages: ['home', 'servicios', 'investor-pass', 'inversionista', 'sobre-mi', 'faq', 'blog', 'contacto'],
  },

  'superspuma': {
    slug: 'superspuma',
    vertical: 'retail-local',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'tienda', 'combos', 'faq', 'contacto', 'envios', 'garantia', 'financiacion', 'guias', 'nosotros', 'privacidad', 'promociones', 'terminos', 'tiendas', 'cambio', 'producto', 'guia-compra'],
  },
  'demo-peluqueria': {
    slug: 'demo-peluqueria',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-salon-belleza': {
    slug: 'demo-salon-belleza',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-barberia': {
    slug: 'demo-barberia',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-unas': {
    slug: 'demo-unas',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-depilacion': {
    slug: 'demo-depilacion',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-maquillaje': {
    slug: 'demo-maquillaje',
    vertical: 'beauty-personal-care',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-restaurant': {
    slug: 'demo-restaurant',
    vertical: 'food-beverage',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-panaderia': {
    slug: 'demo-panaderia',
    vertical: 'food-beverage',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-parrilla': {
    slug: 'demo-parrilla',
    vertical: 'food-beverage',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-cafeteria': {
    slug: 'demo-cafeteria',
    vertical: 'food-beverage',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-clinica-integral': {
    slug: 'demo-clinica-integral',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-odontologia': {
    slug: 'demo-odontologia',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-psicologia': {
    slug: 'demo-psicologia',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-farmacia': {
    slug: 'demo-farmacia',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-inmobiliaria': {
    slug: 'demo-inmobiliaria',
    vertical: 'real-estate-relocation',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-spa': {
    slug: 'demo-spa',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-taller-mecanico': {
    slug: 'demo-taller-mecanico',
    vertical: 'automotive',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-ferreteria': {
    slug: 'demo-ferreteria',
    vertical: 'retail-local',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-electricista': {
    slug: 'demo-electricista',
    vertical: 'trades-home-services',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-plomero': {
    slug: 'demo-plomero',
    vertical: 'trades-home-services',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-carniceria': {
    slug: 'demo-carniceria',
    vertical: 'retail-local',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-gomeria': {
    slug: 'demo-gomeria',
    vertical: 'automotive',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-lavadero': {
    slug: 'demo-lavadero',
    vertical: 'automotive',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-bodega': {
    slug: 'demo-bodega',
    vertical: 'retail-local',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-cerrajero': {
    slug: 'demo-cerrajero',
    vertical: 'trades-home-services',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-veterinaria': {
    slug: 'demo-veterinaria',
    vertical: 'pets-animals',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },
  'demo-herreria': {
    slug: 'demo-herreria',
    vertical: 'trades-home-services',
    country: 'Paraguay',
    domain: '',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'contacto'],
  },

  'preview-galilea-estetica': {
    slug: 'preview-galilea-estetica',
    vertical: 'beauty-personal-care',
    country: 'Paraguay', domain: '', defaultLocale: 'es', locales: ['es'],
    pages: ['home', 'servicios', 'galeria', 'gift-cards', 'contacto'],
  },
  'preview-studio22': {
    slug: 'preview-studio22',
    vertical: 'portfolio-professional',
    country: 'Paraguay', domain: '', defaultLocale: 'es', locales: ['es'],
    pages: ['home', 'servicios', 'galeria', 'contacto'],
  },
  'preview-hidrobaby': {
    slug: 'preview-hidrobaby',
    vertical: 'health-wellness',
    country: 'Paraguay',
    domain: 'hidrobaby-spa.paragu-ai.com',
    defaultLocale: 'es',
    locales: ['es'],
    pages: ['home', 'servicios', 'sucursales', 'faq', 'gift-cards', 'contacto'],
  },
  'preview-guillen-barber': {
    slug: 'preview-guillen-barber',
    vertical: 'service-booking',
    country: 'Paraguay', domain: '', defaultLocale: 'es', locales: ['es'],
    pages: ['home', 'servicios', 'galeria', 'contacto'],
  },
  'preview-fullfitness': {
    slug: 'preview-fullfitness',
    vertical: 'sports-recreation',
    country: 'Paraguay', domain: '', defaultLocale: 'es', locales: ['es'],
    pages: ['home', 'planes', 'clases', 'galeria', 'contacto'],
  },
  'brahm-the-raccoon': {
    slug: 'brahm-the-raccoon',
    vertical: 'portfolio-professional',
    country: 'Paraguay',
    domain: 'brahmtheraccoon.com',
    defaultLocale: 'es',
    locales: ['en', 'es'],
    pages: ['home', 'music', 'lyrics', 'gallery', 'journal', 'press', 'credits', 'guestbook'],
  },
} as const

export type SiteSlug = keyof typeof SITES

export const DEFAULT_SITE = SITES['nexa-paraguay']