/**
 * Static-config facade — assembles REGISTRY_MAP and CONTENT_MAP from per-
 * vertical shards in web/lib/engine/data/*.ts. Each shard is its own module
 * (~60-160 KB) which is far easier on the TS language server and IDE than
 * the old 1.8 MB monolith.
 *
 * Generated by web/scripts/generate-static-config-sharded.ts — regenerate
 * with `npm run generate:config` after adding or changing type files.
 */

import * as beautyPersonalCareShard from './data/beauty-personal-care'
import * as healthWellnessShard from './data/health-wellness'
import * as foodBeverageShard from './data/food-beverage'
import * as hospitalityTourismShard from './data/hospitality-tourism'
import * as serviceBookingShard from './data/service-booking'
import * as portfolioProfessionalShard from './data/portfolio-professional'
import * as tradesHomeServicesShard from './data/trades-home-services'
import * as automotiveShard from './data/automotive'
import * as retailLocalShard from './data/retail-local'
import * as educationTrainingShard from './data/education-training'
import * as b2bProfessionalShard from './data/b2b-professional'
import * as realEstateRelocationShard from './data/real-estate-relocation'
import * as tradesIndustrialShard from './data/trades-industrial'
import * as agricultureAgribusinessShard from './data/agriculture-agribusiness'
import * as logisticsTransportShard from './data/logistics-transport'
import * as financeInsuranceShard from './data/finance-insurance'
import * as technologyDigitalShard from './data/technology-digital'
import * as artsEntertainmentVenuesShard from './data/arts-entertainment-venues'
import * as sportsRecreationShard from './data/sports-recreation'
import * as petsAnimalsShard from './data/pets-animals'
import * as mediaPublishingShard from './data/media-publishing'
import * as membershipCommunityShard from './data/membership-community'
import * as deathCareShard from './data/death-care'

function assemble(): { REGISTRY: Record<string, unknown>; CONTENT: Record<string, unknown> } {
  const reg: Record<string, unknown> = {}
  const con: Record<string, unknown> = {}
  Object.assign(reg, beautyPersonalCareShard.REGISTRY); Object.assign(con, beautyPersonalCareShard.CONTENT)
  Object.assign(reg, healthWellnessShard.REGISTRY); Object.assign(con, healthWellnessShard.CONTENT)
  Object.assign(reg, foodBeverageShard.REGISTRY); Object.assign(con, foodBeverageShard.CONTENT)
  Object.assign(reg, hospitalityTourismShard.REGISTRY); Object.assign(con, hospitalityTourismShard.CONTENT)
  Object.assign(reg, serviceBookingShard.REGISTRY); Object.assign(con, serviceBookingShard.CONTENT)
  Object.assign(reg, portfolioProfessionalShard.REGISTRY); Object.assign(con, portfolioProfessionalShard.CONTENT)
  Object.assign(reg, tradesHomeServicesShard.REGISTRY); Object.assign(con, tradesHomeServicesShard.CONTENT)
  Object.assign(reg, automotiveShard.REGISTRY); Object.assign(con, automotiveShard.CONTENT)
  Object.assign(reg, retailLocalShard.REGISTRY); Object.assign(con, retailLocalShard.CONTENT)
  Object.assign(reg, educationTrainingShard.REGISTRY); Object.assign(con, educationTrainingShard.CONTENT)
  Object.assign(reg, b2bProfessionalShard.REGISTRY); Object.assign(con, b2bProfessionalShard.CONTENT)
  Object.assign(reg, realEstateRelocationShard.REGISTRY); Object.assign(con, realEstateRelocationShard.CONTENT)
  Object.assign(reg, tradesIndustrialShard.REGISTRY); Object.assign(con, tradesIndustrialShard.CONTENT)
  Object.assign(reg, agricultureAgribusinessShard.REGISTRY); Object.assign(con, agricultureAgribusinessShard.CONTENT)
  Object.assign(reg, logisticsTransportShard.REGISTRY); Object.assign(con, logisticsTransportShard.CONTENT)
  Object.assign(reg, financeInsuranceShard.REGISTRY); Object.assign(con, financeInsuranceShard.CONTENT)
  Object.assign(reg, technologyDigitalShard.REGISTRY); Object.assign(con, technologyDigitalShard.CONTENT)
  Object.assign(reg, artsEntertainmentVenuesShard.REGISTRY); Object.assign(con, artsEntertainmentVenuesShard.CONTENT)
  Object.assign(reg, sportsRecreationShard.REGISTRY); Object.assign(con, sportsRecreationShard.CONTENT)
  Object.assign(reg, petsAnimalsShard.REGISTRY); Object.assign(con, petsAnimalsShard.CONTENT)
  Object.assign(reg, mediaPublishingShard.REGISTRY); Object.assign(con, mediaPublishingShard.CONTENT)
  Object.assign(reg, membershipCommunityShard.REGISTRY); Object.assign(con, membershipCommunityShard.CONTENT)
  Object.assign(reg, deathCareShard.REGISTRY); Object.assign(con, deathCareShard.CONTENT)
  return { REGISTRY: reg, CONTENT: con }
}

const assembled = assemble()

export const REGISTRY_MAP: Record<string, unknown> = assembled.REGISTRY
export const CONTENT_MAP: Record<string, unknown> = assembled.CONTENT

export function getRegistry(type: string): unknown | null {
  return REGISTRY_MAP[type] ?? null
}

export function getContent(type: string): unknown | null {
  return CONTENT_MAP[type] ?? null
}
