services:
  web:
    image: fun4me-store:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.fun4me-store.entrypoints=websecure"
        - "traefik.http.routers.fun4me-store.rule=Host(`fun4me-store.paragu-ai.com`)"
        - "traefik.http.routers.fun4me-store.tls=true"
        - "traefik.http.routers.fun4me-store.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.fun4me-store.middlewares=security-headers@file"
        - "traefik.http.services.fun4me-store.loadbalancer.server.port=80"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
