FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000
COPY .next/standalone ./
COPY .next/static ./apps/pierce-charm/.next/static
COPY public ./apps/pierce-charm/public
EXPOSE 3000
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
USER nextjs
CMD ["node", "apps/pierce-charm/server.js"]</content>
