FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/scott-tatuajes/.next/static
COPY public ./apps/scott-tatuajes/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/scott-tatuajes/server.js"]
