FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/arnos-barber-shop/.next/static
COPY public ./apps/arnos-barber-shop/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/arnos-barber-shop/server.js"]
