FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/dayah-litworks/.next/static
COPY public ./apps/dayah-litworks/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/dayah-litworks/server.js"]
