#!/usr/bin/env node
/**
 * Auto-generate the section renderer mapping from the section registry.
 *
 * Scans the SECTION_CATALOG in section-registry.ts, then checks which
 * components exist as files in components/sections/. Produces a TS file
 * with imports + COMPONENTS map that the renderers can use.
 *
 * Run: tsx scripts/generate-renderer-map.ts
 * Output: lib/engine/generated/renderer-map.ts
 * Add to prebuild: "generate:renderer": "tsx scripts/generate-renderer-map.ts"
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')

const REGISTRY_PATH = path.resolve(PROJECT_ROOT, 'lib/engine/section-registry.ts')
const SECTIONS_DIR = path.resolve(PROJECT_ROOT, 'components/sections')
const OUTPUT_DIR = path.resolve(PROJECT_ROOT, 'lib/engine/generated')
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'renderer-map.ts')

// Read the section registry to extract all registered IDs
const registry = fs.readFileSync(REGISTRY_PATH, 'utf-8')

// Extract section IDs from the SECTION_CATALOG
// Pattern: "'section-id': {" or "sectionId: {"
const sectionIds: string[] = []
const catalogRegex = /  '?([a-z0-9-]+)'?:\s*\{/g
let match
while ((match = catalogRegex.exec(registry)) !== null) {
  sectionIds.push(match[1])
}

// Scan available section component files (now in subdirectories)
const sectionFiles: string[] = []
function scanDir(dir: string) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) scanDir(full)
    else if (entry.name.endsWith('-section.tsx') || entry.name.endsWith('.tsx'))
      sectionFiles.push(entry.name)
  }
}
scanDir(SECTIONS_DIR)

// Build a map: section-id → component file info
interface ComponentInfo {
  sectionId: string
  fileName: string
  exportName: string
  subdir: string
  /** true → `import X from ...`, false → `import { X } from ...` */
  isDefault: boolean
}

// Find which subdirectory a file is in
function findFile(name: string): string | null {
  for (const entry of fs.readdirSync(SECTIONS_DIR, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const p = path.join(SECTIONS_DIR, entry.name, name)
      if (fs.existsSync(p)) return entry.name
    }
  }
  return null
}

const components: ComponentInfo[] = []

for (const sid of sectionIds) {
    // The section file could be named:
    // 1. {sectionId}-section.tsx  (standard)
    // 2. {sectionId}.tsx (edge case, e.g. whatsapp-float.tsx)
    const possibleNames = [`${sid}-section.tsx`, `${sid}.tsx`]
  const found = possibleNames.find((name) => sectionFiles.includes(name))

  if (found) {
    const subdir = findFile(found) || '.'
    const filePath = path.join(SECTIONS_DIR, subdir, found)
    const content = fs.readFileSync(filePath, 'utf-8')

    // Collect every top-level named export plus any `export default X`
    // identifier. Modules like `product-catalog-section.tsx` export helper
    // functions (`buildWhatsAppUrl`) BEFORE the actual section component —
    // matching "first export" would wire the helper into the component map.
    const allExports: string[] = []
    const exportRe = /export (?:function|const|class) (\w+)/g
    let em: RegExpExecArray | null
    while ((em = exportRe.exec(content)) !== null) {
      allExports.push(em[1])
    }

    // Also capture the default export identifier if any (`export default Foo`).
    const defaultMatch = content.match(/export\s+default\s+([A-Za-z_$][\w$]*)/)
    const defaultName = defaultMatch ? defaultMatch[1] : null

    // Filter: skip helper-looking names — SCREAMING_SNAKE_CASE constants
    // (STOCK_CONFIG, FAQ_DATA, DEFAULT_DELIVERY_ZONES, WHATSAPP_TEMPLATES),
    // camelCase helpers (buildWhatsAppUrl), and interface/type-alias names.
    const isComponentLike = (n: string) =>
      /^[A-Z]/.test(n) && !/^[A-Z0-9_]+$/.test(n)

    const chosen =
      allExports.find((n) => /Section$/.test(n) && isComponentLike(n)) ||
      allExports.find(
        (n) =>
          /(Float|Wizard|Embed|Gate|Feed|Header|Footer|Strip|Gallery|Stories)$/.test(n) &&
          isComponentLike(n),
      ) ||
      (defaultName && isComponentLike(defaultName) ? defaultName : null) ||
      allExports.find(isComponentLike) ||
      allExports[0]

    if (chosen) {
      components.push({
        sectionId: sid,
        fileName: found,
        subdir,
        exportName: chosen,
        isDefault: chosen === defaultName && !allExports.includes(chosen),
      })
    }
  }
}

// Generate the TypeScript file
const lines: string[] = [
  '// Auto-generated by scripts/generate-renderer-map.ts',
  '// Regenerar con: npm run generate:renderer',
  '// DO NOT EDIT MANUALLY',
  '',
  "import type React from 'react'",
  '',
]

// Add imports (files are in subdirectories now)
for (const c of components) {
  const subPath = c.subdir ? `${c.subdir}/` : ''
  const importPath = `@/components/sections/${subPath}${c.fileName.replace('.tsx', '')}`
  if (c.isDefault) {
    lines.push(`import ${c.exportName} from '${importPath}'`)
  } else {
    lines.push(`import { ${c.exportName} } from '${importPath}'`)
  }
}

lines.push('')
lines.push('export const GENERATED_MAP: Record<string, React.ComponentType<any>> = {')

for (const c of components) {
  if (c.sectionId.includes('-')) {
    lines.push(`  '${c.sectionId}': ${c.exportName},`)
  } else {
    lines.push(`  ${c.sectionId}: ${c.exportName},`)
  }
}

lines.push('}')
lines.push('')

fs.mkdirSync(OUTPUT_DIR, { recursive: true })
fs.writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8')

console.log(`[generate-renderer-map] Scanned ${sectionIds.length} registered sections`)
console.log(`[generate-renderer-map] Found ${components.length} with matching component files`)
console.log(`[generate-renderer-map] Wrote ${OUTPUT_PATH}`)

// Report unmatched sections
const foundIds = new Set(components.map((c) => c.sectionId))
const missing = sectionIds.filter((id) => !foundIds.has(id))
if (missing.length > 0) {
  console.log(`[generate-renderer-map] WARNING: ${missing.length} sections have NO component file:`)
  missing.forEach((id) => console.log(`  - ${id}`))
}
