services:
  web:
    image: trentina-cerveza:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.trentina-cerveza.entrypoints=websecure"
        - "traefik.http.routers.trentina-cerveza.rule=Host(`trentina-cerveza.paragu-ai.com`)"
        - "traefik.http.routers.trentina-cerveza.tls=true"
        - "traefik.http.routers.trentina-cerveza.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.trentina-cerveza.middlewares=security-headers@file"
        - "traefik.http.services.trentina-cerveza.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
