FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/meal-prep/.next/static
COPY public ./apps/meal-prep/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/meal-prep/server.js"]
