FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/escribania-paraguay/.next/static
COPY public ./apps/escribania-paraguay/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/escribania-paraguay/server.js"]
