services:
  web:
    image: escribania-paraguay:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.escribania-paraguay.entrypoints=websecure"
        - "traefik.http.routers.escribania-paraguay.rule=Host(`escribania-paraguay.paragu-ai.com`)"
        - "traefik.http.routers.escribania-paraguay.tls=true"
        - "traefik.http.routers.escribania-paraguay.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.escribania-paraguay.middlewares=security-headers@file"
        - "traefik.http.services.escribania-paraguay.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
