services:
  web:
    image: nudo:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.nudo.entrypoints=websecure"
        - "traefik.http.routers.nudo.rule=Host(`nudo.paragu-ai.com`)"
        - "traefik.http.routers.nudo.tls=true"
        - "traefik.http.routers.nudo.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.nudo.middlewares=security-headers@file"
        - "traefik.http.services.nudo.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
