services:
  web:
    image: pitchy-website:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.pitchy-website.entrypoints=websecure"
        - "traefik.http.routers.pitchy-website.rule=Host(`pitchy-website.paragu-ai.com`)"
        - "traefik.http.routers.pitchy-website.tls=true"
        - "traefik.http.routers.pitchy-website.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.pitchy-website.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
