FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/estudio-medieval/.next/static
COPY public ./apps/estudio-medieval/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/estudio-medieval/server.js"]
