services:
  web:
    image: villamayor-asociados:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.villamayor-asociados.entrypoints=websecure"
        - "traefik.http.routers.villamayor-asociados.rule=Host(`villamayor.paragu-ai.com`)"
        - "traefik.http.routers.villamayor-asociados.tls=true"
        - "traefik.http.routers.villamayor-asociados.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.villamayor-asociados.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
