/** @jsxImportSource react */
"use client"

import {
  HeroSection, StatsSection, TrustSection, ProgramsSection,
  ServicesSection, WhyCountrySection, FeaturesSection, ProcessSection,
  TestimonialsSection, RequirementsSection, CtaBanner,
  FaqSection, FaqSearchSection, BlogSection, TeamSection,
  StorySection, PillarsSection, NewsletterSection, ContactDetailsSection,
  GallerySection, ComparisonSection, GlossarySection, PageHeroSection,
  HighlightSection, BookingEmbedSection, CaseStudySection,
  ServiceDetailSection, GenericSection, PrivacyAccordion,
  IntakeWizardSection, PressReleasesListSection,
  FeedbackSection, BookingFormSection,
} from "./index"
import { SectionComponentProps } from "./types"

export const DEFAULT_SECTIONS: Record<string, React.ComponentType<SectionComponentProps>> = {
  "hero": HeroSection,
  "hero-section": HeroSection,
  "stats": StatsSection,
  "stats-grid": StatsSection,
  "trust-signals": TrustSection,
  "programs": ProgramsSection,
  "services": ServicesSection,
  "why-destination": WhyCountrySection,
  "why-country": WhyCountrySection,
  "features": FeaturesSection,
  "process-timeline": ProcessSection,
  "process": ProcessSection,
  "testimonials": TestimonialsSection,
  "requirements": RequirementsSection,
  "cta-banner": CtaBanner,
  "cta": CtaBanner,
  "faq": FaqSection,
  "faq-search": FaqSearchSection,
  "blog": BlogSection,
  "team": TeamSection,
  "story": StorySection,
  "pillars": PillarsSection,
  "newsletter": NewsletterSection,
  "contact": ContactDetailsSection,
  "contact-details": ContactDetailsSection,
  "contact-form": ContactDetailsSection,
  "gallery": GallerySection,
  "comparison": ComparisonSection,
  "glossary": GlossarySection,
  "page-hero": PageHeroSection,
  "highlights": HighlightSection,
  "booking-embed": BookingEmbedSection,
  "case-study": CaseStudySection,
  "caseStudy": CaseStudySection,
  "service-detail": ServiceDetailSection,
  "privacy": PrivacyAccordion,
  "guides": GenericSection,
  "press-releases": PressReleasesListSection,
  "intakeWizard": IntakeWizardSection,
  "intake-wizard": IntakeWizardSection,
  "booking-form": BookingFormSection,
  "feedback": FeedbackSection,
}
