FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/portas-barber/.next/static
COPY public ./apps/portas-barber/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/portas-barber/server.js"]
