FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/cuidadoamiga/.next/static
COPY public ./apps/cuidadoamiga/public
COPY .env* ./
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
ENV NEXT_PUBLIC_SITE_URL="https://cuidadoamiga.paragu-ai.com"
CMD ["node", "apps/cuidadoamiga/server.js"]
