FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/cronos-academy/.next/static
COPY public ./apps/cronos-academy/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/cronos-academy/server.js"]
