import nextConfig from 'eslint-config-next'
import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      '.open-next/**',
      '.vercel/**',
      'coverage/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'out/**',
      // Auto-generated tenant-data module (~760 KB). Regenerated by
      // `scripts/generate-tenant-data.ts` on every prebuild.
      'lib/engine/generated/**',
    ],
  },
  ...nextConfig,
  ...coreWebVitals,
  ...typescript,

  // Runtime code must use @/lib/logger — never raw console.*.
  // Scope-restricted so scripts/**, tests/**, and the logger itself can still
  // call console as needed.
  {
    files: ['app/**/*.{ts,tsx}', 'lib/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}', 'middleware.ts'],
    ignores: ['lib/obs/logger.ts'],
    rules: {
      'no-console': 'error',
    },
  },

  // Every <a target="_blank"> must include rel="noopener noreferrer" to
  // prevent the target page from accessing window.opener (reverse-tabnabbing).
  // The next-config preset turns this off; we override back to error.
  {
    files: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
    rules: {
      'react/jsx-no-target-blank': ['error', { allowReferrer: false, enforceDynamicLinks: 'always' }],
    },
  },

  // Legacy CommonJS scripts under web/scripts/**.js are dev-only utilities
  // (image optimization, content generation, etc.) — they are not part of the
  // shipped runtime and predate the move to ESM. Allow require() there.
  // Tests and ad-hoc audit scripts may also leave unused vars while iterating.
  {
    files: ['scripts/**/*.js', 'scripts/**/*.ts', 'tests/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },

  // Section / landing components must use the <Heading> primitive — never
  // raw <h1>/<h2>/<h3>. The primitive owns font-family + responsive scale.
  // All existing violations were migrated on 2026-04-20; this is now
  // enforced as an ERROR to prevent regressions.
  {
    files: ['components/sections/**/*.{ts,tsx}', 'components/landing/**/*.{ts,tsx}'],
    ignores: ['components/ui/heading.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "JSXOpeningElement[name.name='h1']",
          message: 'Use <Heading level={1}> from @/components/ui/heading instead of raw <h1>.',
        },
        {
          selector: "JSXOpeningElement[name.name='h2']",
          message: 'Use <Heading level={2}> instead of raw <h2>.',
        },
        {
          selector: "JSXOpeningElement[name.name='h3']",
          message: 'Use <Heading level={3}> instead of raw <h3>.',
        },
      ],
    },
  },
]

export default eslintConfig
