services:
  web:
    image: magnolia-peluqueria:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.magnolia-peluqueria.entrypoints=websecure"
        - "traefik.http.routers.magnolia-peluqueria.rule=Host(`magnolia-peluqueria.paragu-ai.com`)"
        - "traefik.http.routers.magnolia-peluqueria.tls=true"
        - "traefik.http.routers.magnolia-peluqueria.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.magnolia-peluqueria.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
