services:
  web:
    image: granja-cabral:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.granja-cabral.entrypoints=websecure"
        - "traefik.http.routers.granja-cabral.rule=Host(`granja-cabral.paragu-ai.com`)"
        - "traefik.http.routers.granja-cabral.tls=true"
        - "traefik.http.routers.granja-cabral.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.granja-cabral.middlewares=security-headers@file"
        - "traefik.http.services.granja-cabral.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
