services:
  web:
    image: luis-de-leon-concept:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.luis-de-leon-concept.entrypoints=websecure"
        - "traefik.http.routers.luis-de-leon-concept.rule=Host(`luis-de-leon-concept.paragu-ai.com`)"
        - "traefik.http.routers.luis-de-leon-concept.tls=true"
        - "traefik.http.routers.luis-de-leon-concept.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.luis-de-leon-concept.middlewares=security-headers@file"
        - "traefik.http.services.luis-de-leon-concept.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
