FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/luis-de-leon-concept/.next/static
COPY public ./apps/luis-de-leon-concept/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/luis-de-leon-concept/server.js"]
