services:
  web:
    image: jota-ink-tattoo:prod
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=agent-net"
        - "traefik.http.routers.jota-ink-tattoo.entrypoints=websecure"
        - "traefik.http.routers.jota-ink-tattoo.rule=Host(`jota-ink-tattoo.paragu-ai.com`)"
        - "traefik.http.routers.jota-ink-tattoo.tls=true"
        - "traefik.http.routers.jota-ink-tattoo.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.jota-ink-tattoo.loadbalancer.server.port=3000"
    networks:
      - agent-net
networks:
  agent-net:
    external: true
