FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/trentina-site/.next/static
COPY public ./apps/trentina-site/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/trentina-site/server.js"]
