FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY .next/standalone ./
COPY .next/static ./apps/reina-de-copas/.next/static
COPY public ./apps/reina-de-copas/public
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "apps/reina-de-copas/server.js"]